# Generated by Django 5.2.4 on 2025-07-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
