# Generated by Django 5.2.4 on 2025-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stock_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
