# Generated by Django 5.2.4 on 2025-07-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_stock_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
    ]
