# Generated by Django 5.2.4 on 2025-07-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_note_portfoliosnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='stock_symbol',
            new_name='symbol',
        ),
    ]
